name: Winnie Kuo
favicon: null
layout_spectrum: 0.5242396926041692
typography_spectrum: 0.04401689348742366
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5786860161460936
  lightness: 0.5100330207496881
  saturation: 0.9103997428901494
  rhythmicContrast: 0.3842462671454996
purpose: []
